spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_procure?characterEncoding=UTF-8 # useUnicode=true&serverTimezone=UTC
    username: library_procure
    password: 123456

    druid:
      aop-patterns: library-procure.*  # 监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin   # 账号
        login-password: 123456  # 密码
        resetEnable: false
        allow: ""
        deny: ""

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '/druid/*,/swagger-ui.html,/swagger-ui.html/*,/webjars/*,/swagger-resources,/swagger-resources/*,/v2/*,/csrf,/favicon.ico'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true



  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false


server:
  port: 8081